apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: k8sreq-duplicator-controller-
resources:
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- requestclones_editor_role.yaml
- requestclones_viewer_role.yaml
